# Generated by Django 4.2.27 on 2026-03-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_block_id_alter_mininginfo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='tamper_alert_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vote',
            name='tamper_alert_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mininginfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
